services:
  appointment_ms:
    image: appointment_ms
    build:
      context: .
      dockerfile: Appointment_MS/Dockerfile

  user_service:
    image: user_service
    build:
      context: .
      dockerfile: User_service/Dockerfile
